WaterResort/Controllers/CurrentReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WaterResort.Data;
using WaterResort.Models;

namespace WaterResort.Controllers
{
    public class CurrentReservationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CurrentReservationsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: CurrentReservations
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            ViewData["Users"] = _userManager;
            ViewData["_context"] =  _context;
            return View(await _context.CurrentReservations.ToListAsync());
        }

        public async Task<IActionResult> Confirmation()
        {
            return View();
        }

        // GET: CurrentReservations/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentReservation = await _context.CurrentReservations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (currentReservation == null)
            {
                return NotFound();
            }

            return View(currentReservation);
        }


        // GET: CurrentReservations/Create
        [Authorize(Roles = "Administrator, Customer")]
        public async Task<IActionResult> Create(int? id)
        {
            ViewData["Room"] = await _context.Rooms.FirstOrDefaultAsync(m => m.Id == id);
            return View();
        }

        // POST: CurrentReservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Customer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountId,StartDate,EndDate,TotalCost,RoomId")] CurrentReservation currentReservation)
        {
            var room = await _context.Rooms.FirstOrDefaultAsync(m => m.Id == currentReservation.RoomId);
            if (User.IsInRole("Customer"))
            {
                if (room.Reserved == true)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(currentReservation);

                var AR = await _context.AccountsReceivables.FirstOrDefaultAsync(m => m.AccountId == currentReservation.AccountId) as AccountsReceivable;

                //Check if the user already has a standing balance.
                if(AR != null)
                {
                    AR.Balance = AR.Balance + currentReservation.TotalCost;
                }
                else
                {
                    AccountsReceivable accountsReceivable = new AccountsReceivable();
                    accountsReceivable.AccountId = currentReservation.AccountId;
                    accountsReceivable.Balance = currentReservation.TotalCost;
                    _context.AccountsReceivables.Add(accountsReceivable);
                }
                
                //Check if the reservation starting date is today
                if (currentReservation.StartDate == DateTime.Today)
                {
                    
                    room.Reserved = true;
                    room.AccountId = currentReservation.AccountId;
                }


                await _context.SaveChangesAsync();
                if (User.IsInRole("Administrator"))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction("Confirmation", currentReservation);
                }
                
            }

            return View(currentReservation);
        }

        // GET: CurrentReservations/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var currentReservation = await _context.CurrentReservations.FindAsync(id);

            ViewData["Room"] = await _context.Rooms.FirstOrDefaultAsync(m => m.Id == currentReservation.RoomId);

            
            if (currentReservation == null)
            {
                return NotFound();
            }
            return View(currentReservation);
        }

        // POST: CurrentReservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AccountId,StartDate,EndDate,TotalCost,RoomId")] CurrentReservation currentReservation)
        {
            if (id != currentReservation.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await DeleteConfirmed(id);

                    var room = await _context.Rooms.FirstOrDefaultAsync(m => m.Id == currentReservation.RoomId);

                    CurrentReservation cr = new CurrentReservation();
                    cr.AccountId = currentReservation.AccountId;
                    cr.StartDate = currentReservation.StartDate;
                    cr.EndDate = currentReservation.EndDate;
                    cr.TotalCost = (decimal)(currentReservation.EndDate - currentReservation.StartDate).TotalDays * room.CostPerNight;
                    cr.RoomId = currentReservation.RoomId;

                    if(cr.StartDate <= DateTime.Today && cr.EndDate >= DateTime.Today)
                    {
                        room.Reserved = true;
                        room.AccountId = currentReservation.AccountId;
                    } else
                    {
                        room.Reserved = false;
                        room.AccountId = null;
                    }

                    await Create(cr);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CurrentReservationExists(currentReservation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(currentReservation);
        }

        // GET: CurrentReservations/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentReservation = await _context.CurrentReservations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (currentReservation == null)
            {
                return NotFound();
            }

            return View(currentReservation);
        }

        // POST: CurrentReservations/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var currentReservation = await _context.CurrentReservations.FindAsync(id);

            var room = await _context.Rooms.FirstOrDefaultAsync(m => m.Id == currentReservation.RoomId);

            //Update the balance in the accounts receivables
            var AR = await _context.AccountsReceivables.FirstOrDefaultAsync(m =>
                m.AccountId == currentReservation.AccountId) as AccountsReceivable;
            var totalDays = (currentReservation.EndDate - currentReservation.StartDate).TotalDays;
            var totalCost = (decimal)totalDays * room.CostPerNight;
            AR.Balance = AR.Balance - totalCost;

            //Remove reservation status of room and user's accountId if the room is currently reserved
            if (room.Reserved == true)
            {
                room.Reserved = false;
                room.AccountId = null;
            }

            _context.CurrentReservations.Remove(currentReservation);
            await _context.SaveChangesAsync();

            
            return RedirectToAction(nameof(Index));
        }

        private bool CurrentReservationExists(int id)
        {
            return _context.CurrentReservations.Any(e => e.Id == id);
        }
    }
}

WaterResort/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WaterResort.Data;
using WaterResort.Models;

namespace WaterResort.Controllers
{
    
    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rooms.ToListAsync());
        }

        [Authorize(Roles = "Administrator, Customer")]
        // GET: Rooms/ConfirmReservation/5
        public async Task<IActionResult> ConfirmReservation(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/ConfirmReservation/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Customer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmReservation(int id, [Bind("Id,AccountId,QueenBeds,KingBeds,Reserved,Cleaned,LakeFacing,Suite")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        [Authorize(Roles = "Administrator")]
        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        [Authorize(Roles = "Administrator")]
        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AccountId,QueenBeds,KingBeds,Reserved,Cleaned,LakeFacing,Suite")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AccountId,QueenBeds,KingBeds,Reserved,Cleaned,LakeFacing,Suite")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Click(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FirstOrDefaultAsync(m => m.Id == id);

            if (room != null)
            {

                TempData["RoomNumber"] = room.RoomNumber;
                TempData["CostPerNight"] = "$" + room.CostPerNight.ToString();

                if (room.LakeFacing == true)
                {
                    TempData["LakeFacing"] = "Yes.";
                }
                else
                {
                    TempData["LakeFacing"] = "No.";
                }

                if (room.QueenBeds == true)
                {
                    TempData["Beds"] = "Two queen beds.";
                }
                else
                {
                    TempData["Beds"] = "One king bed.";
                }

                if (room.Suite == true)
                {
                    TempData["RoomType"] = "Suite";
                }
                else
                {
                    TempData["RoomType"] = "Standard";
                }
                TempData["Id"] = room.Id;

                //This statement can only be ran if an administrator has selected a reserved room
                if (room.Reserved == true)
                {
                    var customerId = room.AccountId;
                    var customer = await _context.Users.FirstOrDefaultAsync(m => m.Id == customerId);
                    var currentRes = await _context.CurrentReservations.FirstOrDefaultAsync(m => m.RoomId == room.Id);

                    TempData["PhoneNumber"] = customer.PhoneNumber;
                    TempData["Email"] = customer.Email;
                    TempData["ResId"] = currentRes.Id;

                }
                return RedirectToAction("Index");
            } 
            else
            {
                return NotFound();
            }
        }
    }
}

WaterResort/Views/Rooms/Create.cshtml
@model WaterResort.Models.Room

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="QueenBeds" class="control-label"></label>
                <input asp-for="QueenBeds" class="form-control" />
                <span asp-validation-for="QueenBeds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KingBeds" class="control-label"></label>
                <input asp-for="KingBeds" class="form-control" />
                <span asp-validation-for="KingBeds" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Reserved" /> @Html.DisplayNameFor(model => model.Reserved)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Cleaned" /> @Html.DisplayNameFor(model => model.Cleaned)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="LakeFacing" /> @Html.DisplayNameFor(model => model.LakeFacing)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Suite" /> @Html.DisplayNameFor(model => model.Suite)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WaterResort/Views/Rooms/Delete.cshtml
@model WaterResort.Models.Room

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QueenBeds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QueenBeds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KingBeds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KingBeds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reserved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reserved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cleaned)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cleaned)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LakeFacing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LakeFacing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Suite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Suite)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WaterResort/Views/Rooms/Details.cshtml
@model WaterResort.Models.Room

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QueenBeds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QueenBeds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KingBeds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KingBeds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reserved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reserved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cleaned)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cleaned)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LakeFacing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LakeFacing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Suite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Suite)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WaterResort/Views/Rooms/Edit.cshtml
@model WaterResort.Models.Room

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <input asp-for="AccountId" class="form-control" />
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QueenBeds" class="control-label"></label>
                <input asp-for="QueenBeds" class="form-control" />
                <span asp-validation-for="QueenBeds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KingBeds" class="control-label"></label>
                <input asp-for="KingBeds" class="form-control" />
                <span asp-validation-for="KingBeds" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Reserved" /> @Html.DisplayNameFor(model => model.Reserved)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Cleaned" /> @Html.DisplayNameFor(model => model.Cleaned)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="LakeFacing" /> @Html.DisplayNameFor(model => model.LakeFacing)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Suite" /> @Html.DisplayNameFor(model => model.Suite)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WaterResort/Views/Rooms/Index.cshtml
@model IEnumerable<WaterResort.Models.Room>

@{
    ViewData["Title"] = "Reserve a Room!";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="text-center">Pick a room to get more details!</h1>
<div class="row">
    <div class="col-6">
        <div class="container float-left">
            <h3 class="p-2">
                Floor 1
            </h3>
            <div class="row">
                @{
                    int i = 0;              // Room number counter
                    int floorNum = 1;       // Floor counter
                }
                @foreach (var item in Model)
                {
                <div class="col-1">
                    @{
                        if (item.Reserved == true)
                        {
                            if (User.IsInRole("Administrator"))
                            {
                                <form>
                                    <button type="submit" class="btn btn-danger" style="background-color: #e2717a" asp-action="Click" asp-route-id="@item.Id"></button>
                                </form>
                            }
                            else
                            {
                                <button type="button" class="btn btn-danger" disabled></button>
                            }
                        }
                        else
                        {
                            <form>
                                <button type="submit" class="btn btn-primary" asp-action="Click" asp-route-id="@item.Id"></button>
                            </form>
                        }
                    }
                </div>
                    i++;                // Increase room number counter
                    if (i == 24)        // Last room on floor ends with 24
                    {
                        floorNum++;     // Increase the floor number count
                        FloorNumberHeader(floorNum);
                        i = 0;          // Reset the counter
                    }
                }
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="border border-dark rounded p-2" style="overflow: hidden;">
            <h3 class="text-center">ROOM DETAILS</h3>
            <h5>Room Number: @TempData["RoomNumber"]</h5>
            <h5>Beds: @TempData["Beds"]</h5>
            <h5>Does this room face the lake?: @TempData["LakeFacing"]</h5>
            <h5>Room type: @TempData["RoomType"]</h5>
            <h5>Cost per night: @TempData["CostPerNight"]</h5>
            <a class="btn btn-primary float-right" asp-controller="CurrentReservations" asp-action="Create" asp-route-id="@TempData["Id"]" >Reserve Now!</a>
        </div>

        @if (User.IsInRole("Administrator"))
        {
            <div class="border border-dark rounded p-2 mt-2" style="overflow: hidden;">
                <h3 class="text-center">CUSTOMER DETAILS</h3>
                <h5>Email: @TempData["Email"]</h5>
                <h5>Phone Number: @TempData["PhoneNumber"]</h5>
                <a class="btn btn-primary float-right" asp-controller="CurrentReservations" asp-action="Edit" asp-route-id="@TempData["ResId"]">Edit Reservation</a>
            </div>
        }

    </div>

</div>
@{
    void FloorNumberHeader(int floorNum)
    {
        if (floorNum <= 5)              // There is no floor above 5
        {
            <div class="col-12">
                <h3 class="p-2">
                    Floor @floorNum
                </h3>
            </div>
        }
    }


}